// Export reports to Markdown or Text
import type { ParsedDevice, ValidationResult, TopologyGraph } from '../parsers/types';
import { saveAs } from 'file-saver';

export function generateMarkdownReport(
  projectName: string,
  devices: ParsedDevice[],
  topology: TopologyGraph,
  validation: ValidationResult
): string {
  const lines: string[] = [];

  lines.push(`# ${projectName} — Network Validation Report\n`);
  lines.push(`Generated: ${new Date().toISOString()}\n`);
  lines.push('---\n');

  // Summary
  lines.push('## Summary\n');
  lines.push(`| Metric | Value |\n|--------|-------|\n`);
  lines.push(`| Total Devices | ${devices.length} |\n`);
  lines.push(`| Total Links | ${topology.edges.length} |\n`);
  lines.push(`| Detected Subnets | ${topology.stats.detectedSubnets} |\n`);
  lines.push(`| Errors | ${validation.summary.errors} |\n`);
  lines.push(`| Warnings | ${validation.summary.warnings} |\n`);
  lines.push(`| Info | ${validation.summary.infos} |\n`);
  lines.push('\n');

  // Device table
  lines.push('## Devices\n');
  lines.push('| Hostname | Vendor | Role | Interfaces | Routes | OSPF | BGP | Errors | Warnings |\n');
  lines.push('|----------|--------|------|-----------|--------|------|-----|--------|----------|\n');
  for (const device of devices) {
    const devIssues = validation.issues.filter(i => i.deviceId === device.id);
    const errs = devIssues.filter(i => i.severity === 'error').length;
    const warns = devIssues.filter(i => i.severity === 'warning').length;
    lines.push(`| ${device.hostname} | ${device.vendor} | ${device.role} | ${device.interfaces.length} | ${device.routes.length} | ${device.ospf ? '✓' : '—'} | ${device.bgp ? '✓' : '—'} | ${errs} | ${warns} |\n`);
  }
  lines.push('\n');

  // Interface details per device
  lines.push('## Interface Details\n');
  for (const device of devices) {
    lines.push(`### ${device.hostname}\n`);
    if (device.interfaces.length === 0) {
      lines.push('*No interfaces configured*\n');
    } else {
      lines.push('| Interface | Type | Status | IP Address | Network | MTU | VLAN |\n');
      lines.push('|-----------|------|--------|------------|---------|-----|------|\n');
      for (const iface of device.interfaces) {
        const addrs = iface.addresses.map(a => `${a.address}/${a.prefixLength}`).join(', ') || '—';
        lines.push(`| ${iface.name} | ${iface.type} | ${iface.enabled ? 'up' : 'down'} | ${addrs} | ${iface.addresses[0]?.network || '—'} | ${iface.mtu || '—'} | ${iface.vlanId || '—'} |\n`);
      }
    }
    lines.push('\n');
  }

  // Issues
  if (validation.issues.length > 0) {
    lines.push('## Validation Issues\n');
    for (const issue of validation.issues) {
      const badge = issue.severity === 'error' ? '❌ ERROR' : issue.severity === 'warning' ? '⚠️ WARNING' : 'ℹ️ INFO';
      lines.push(`### ${badge}: ${issue.ruleName}\n`);
      lines.push(`**Message:** ${issue.message}\n`);
      if (issue.deviceHostname) {
        lines.push(`**Device:** ${issue.deviceHostname}${issue.interfaceName ? ` (${issue.interfaceName})` : ''}\n`);
      }
      if (issue.suggestion) {
        lines.push(`**Suggestion:** ${issue.suggestion}\n`);
      }
      lines.push('\n');
    }
  }

  // Topology links
  lines.push('## Topology Links\n');
  lines.push('| Link | Type | Network | Endpoint A | Endpoint B | Status |\n');
  lines.push('|------|------|---------|------------|------------|--------|\n');
  for (const edge of topology.edges) {
    const [a, b] = edge.endpoints;
    lines.push(`| ${edge.id} | ${edge.type} | ${edge.network} | ${a?.deviceHostname || '—'}:${a?.interfaceName || '—'} | ${b?.deviceHostname || '—'}:${b?.interfaceName || '—'} | ${edge.status} |\n`);
  }
  lines.push('\n');

  lines.push('---\n');
  lines.push(`*Report generated by NetThir*\n`);

  return lines.join('');
}

export function generateTextReport(
  projectName: string,
  devices: ParsedDevice[],
  topology: TopologyGraph,
  validation: ValidationResult
): string {
  const lines: string[] = [];

  lines.push(`=== ${projectName} - Network Validation Report ===`);
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');

  lines.push('--- SUMMARY ---');
  lines.push(`Devices: ${devices.length} | Links: ${topology.edges.length} | Subnets: ${topology.stats.detectedSubnets}`);
  lines.push(`Issues: ${validation.summary.errors} errors, ${validation.summary.warnings} warnings, ${validation.summary.infos} info`);
  lines.push('');

  lines.push('--- DEVICES ---');
  for (const device of devices) {
    const devIssues = validation.issues.filter(i => i.deviceId === device.id);
    const errs = devIssues.filter(i => i.severity === 'error').length;
    const warns = devIssues.filter(i => i.severity === 'warning').length;
    lines.push(`  ${device.hostname} (${device.vendor}/${device.role}) - ${device.interfaces.length} interfaces, ${device.routes.length} routes [err:${errs} warn:${warns}]`);
    for (const iface of device.interfaces) {
      const addrs = iface.addresses.map(a => `${a.address}/${a.prefixLength}`).join(', ') || '(no IP)';
      lines.push(`    ${iface.name}: ${addrs} [${iface.type}/${iface.enabled ? 'up' : 'down'}]`);
    }
  }

  if (validation.issues.length > 0) {
    lines.push('');
    lines.push('--- ISSUES ---');
    for (const issue of validation.issues) {
      const lvl = issue.severity === 'error' ? '[ERROR]' : issue.severity === 'warning' ? '[WARN]' : '[INFO]';
      lines.push(`  ${lvl} ${issue.ruleName}: ${issue.message}`);
      if (issue.suggestion) lines.push(`    -> ${issue.suggestion}`);
    }
  }

  lines.push('');
  lines.push('=== END REPORT ===');

  return lines.join('\n');
}

export function downloadMarkdownReport(
  projectName: string,
  devices: ParsedDevice[],
  topology: TopologyGraph,
  validation: ValidationResult
) {
  const content = generateMarkdownReport(projectName, devices, topology, validation);
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  saveAs(blob, `${projectName.replace(/\s+/g, '_')}_report.md`);
}

export function downloadTextReport(
  projectName: string,
  devices: ParsedDevice[],
  topology: TopologyGraph,
  validation: ValidationResult
) {
  const content = generateTextReport(projectName, devices, topology, validation);
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  saveAs(blob, `${projectName.replace(/\s+/g, '_')}_report.txt`);
}